### ISSUE TITLE
Clarify documentation for theme assets

### ISSUE THREAD

**Issue by astehlik** [shopware/docs#791]
The guide [for adding assets to themes](https://developer.shopware.com/docs/guides/plugins/themes/add-assets-to-theme) does not seem to be fully correct. It states:

> Next, please run the bin/console assets:install command. This will copy your plugin assets over to the public/bundles folder:

Looking at the source of `Shopware\Core\Framework\Adapter\Asset\AssetInstallCommand` I did not find any indication that files from the documented folder `app/storefront/src/asset` are copied to the bundles directory.

The files do seem to be copied by the `theme:compile` command instead and they are copied to the theme directory.

Therefore the path documented in the CSS example also seems to be incorrect:

```css
body {
    background-image: url("/bundles/swagbasicexampletheme/your-image.png");
}
```

This is particularly problematic when an S3 storage is used for the filesystems. `build-storefront.sh` seems to place the required files in the bundles directory but it always puts it in the the local `public` folder and not in the S3 storage.

We solved this by using relative paths in our SCSS files, e.g.:

```css
body {
    background-image: url("../asset/your-image.png");
}
```

But maybe there is a better solution.

Please let me know if I can provide any more information or assistance.
